apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.admission.online.openshift.io
spec:
  caBundle: ${CA_BUNDLE}
  group: admission.online.openshift.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
   namespace: mutating-webhook
   name: tolerations-mutator
  version: v1beta1