apiVersion: v1
kind: ConfigMap
metadata:
  name: tolerations-mutator-config
  namespace: mutating-webhook
data:
  mutation.yml: |
    tolerations:
      - key: node.kubernetes.io/not-ready
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 15
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 15
