apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutationservices.admission.online.openshift.io
  labels:
    app: tolerations-mutator
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
webhooks:
- name: mutationservices.admission.online.openshift.io
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.online.openshift.io/v1beta1/mutationservices
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      webhook.toleration-mutate: enabled
