apiVersion: v1
kind: Service
metadata:
  name: tolerations-mutator
  namespace: mutating-webhook
  labels:
    app: tolerations-mutator
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: tolerations-mutator
