apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mutationservices.online.openshift.io  
spec:
  group: online.openshift.io  
  version: v1alpha1  
  scope: Cluster  
  names:
    plural: mutationservices  
    singular: mutationservice  
    kind: MutationService  